# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "Maintain a conversational tone that is supportive in all responses."
early_access: true
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@auto-summary"
  auto_title_placeholder: "@auto-title"
  review_status: false
  commit_status: false
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions:
    - label: "patch"
      instructions: "Apply when the PR contains changes that fix existing functionality."
    - label: "minor"
      instructions: "Apply when changes introduce new functionality but are non-breaking."
    - label: "major"
      instructions: "Apply when changes introduce new functionality that causes breaking changes requiring the user to update their configuration."
    - label: "no-release"
      instructions: "Apply this label when the PR contains changes only to documentation, website content, or other non-Go code. Changes that do not affect the Go code or the application functionality fall under this category."
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "test"
    drafts: false
    base_branches:
      - "main"
  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules:
        - "EN_QUOTES"
      level: "picky"
    hadolint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  linear:
    team_keys:
      - "DEV"
  pull_requests:
    scope: "auto"
