# Visit https://goreleaser.com for documentation on how to customize this behavior.

before:
 hooks:
 - 'go mod tidy'

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
      - freebsd
      - windows
      - linux
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: terramaid
    ldflags:
      # Set `terramaid` version to the GitHub release tag using Go `ldflags`
      - '-s -w'

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  skip: true