# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X "github.com/rosesecurity/Terramaid/cmd.Version={{.Version}}"'
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
