Output terramaid_vhs_demo.gif

Set WindowBar Colorful
Set Margin 20
Set MarginFill "#000000"
Set BorderRadius 10
Set Width 1200
Set Height 600
Set FontSize 24

Type "# Terramaid lets you generate pretty Mermaid diagrams for your Terraform configurations"
Sleep 1s
Enter
Type "# Lets try it out"
Sleep 1s
Enter
Hide
Type "clear"
Enter
Show
Type@100ms "terramaid -o fancy_s3_buckets.md"
Enter
Sleep 3s
Type "vim fancy_s3_buckets.md"
Enter
Sleep 5s
