name: E2E

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache: false
      - run: |
          make build
          terramaid -w test/
          cat Terramaid.md
